/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 */
public class ManageUserAccountsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;

    public ManageUserAccountsJPanel(Business bz, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        refreshTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateNewAccount = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageUser = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnCreateNewAccount.setText("Create New Account");
        btnCreateNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewAccountActionPerformed(evt);
            }
        });
        add(btnCreateNewAccount);
        btnCreateNewAccount.setBounds(130, 350, 210, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(370, 350, 80, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage User Accounts");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(632, 482));

        tblManageUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Name", "Status", "Person", "Last Updated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblManageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblManageUserMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblManageUser);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 600, 150);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 350, 80, 23);

        btnModify.setText("Modify >>");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify);
        btnModify.setBounds(490, 350, 100, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewAccountActionPerformed
        // TODO add your handling code here:
        CreateUserAccountJPanel panel = new CreateUserAccountJPanel(business, this, CardSequencePanel);
        CardSequencePanel.add("CreateUserAccount", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnCreateNewAccountActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selecteduseraccount == null) {
            JOptionPane.showMessageDialog(this, "Please select an account to delete.",
                    "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,
                "Delete account \"" + selecteduseraccount.getUserLoginName() + "\"?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        business.getUserAccountDirectory().deleteUserAccount(selecteduseraccount);
        selecteduseraccount = null;
        refreshTable();
        JOptionPane.showMessageDialog(this, "Account deleted.");

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        if (selecteduseraccount == null) {
            JOptionPane.showMessageDialog(this, "Please select an account to modify.",
                    "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }
        AdminUserAccount detail = new AdminUserAccount(business, selecteduseraccount, this, CardSequencePanel);
        CardSequencePanel.add("AdminUserAccount", detail);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnModifyActionPerformed

    private void tblManageUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblManageUserMousePressed
        // TODO add your handling code here:
        int selectedRow = tblManageUser.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        selecteduseraccount = (UserAccount) tblManageUser.getValueAt(selectedRow, 0);
    }//GEN-LAST:event_tblManageUserMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateNewAccount;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageUser;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"User Name", "Status", "Person", "Last Updated"});

        UserAccountDirectory uad = business.getUserAccountDirectory();
        for (UserAccount ua : uad.getUserAccountList()) {
            Object[] row = new Object[4];
            row[0] = ua;                  // toString() shows username
            row[1] = ua.getStatus();
            row[2] = ua.getPersonId();
            row[3] = ua.getLastUpdatedText();
            model.addRow(row);
        }
        tblManageUser.setModel(model);

    }

}
