/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Profiles.EmployeeDirectory;
import Business.Profiles.EmployeeProfile;
import Business.UserAccounts.UserAccountDirectory;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class AdministerPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    Business business;
    ManagePersonsJPanel parent;

    public AdministerPersonJPanel(Business bz, JPanel jp, ManagePersonsJPanel parent) {

        CardSequencePanel = jp;
        this.business = bz;
        this.parent = parent;
        initComponents();


    }

    public void refreshTable() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtFullName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        txtUsename = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnCreateProfile = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Person Profile");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        btnSave.setText("Save Details");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(150, 200, 120, 23);
        add(txtFullName);
        txtFullName.setBounds(150, 80, 260, 23);
        add(txtEmail);
        txtEmail.setBounds(150, 120, 260, 23);
        add(txtPhone);
        txtPhone.setBounds(150, 160, 260, 23);

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblEmail.setText("Email");
        add(lblEmail);
        lblEmail.setBounds(30, 120, 80, 19);

        lblPhone.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblPhone.setText("Phone");
        add(lblPhone);
        lblPhone.setBounds(30, 160, 80, 19);

        lblFullName.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblFullName.setText("Full Name");
        add(lblFullName);
        lblFullName.setBounds(30, 80, 80, 19);

        lblUserName.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblUserName.setText("Username");
        add(lblUserName);
        lblUserName.setBounds(310, 280, 80, 19);

        lblRole.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblRole.setText("Role ");
        add(lblRole);
        lblRole.setBounds(30, 280, 60, 19);
        add(txtUsename);
        txtUsename.setBounds(400, 280, 160, 23);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbRole);
        cmbRole.setBounds(100, 280, 150, 23);

        btnCreate.setText("Create User Account");
        add(btnCreate);
        btnCreate.setBounds(400, 310, 160, 23);

        btnCreateProfile.setText("Create Profile");
        add(btnCreateProfile);
        btnCreateProfile.setBounds(100, 310, 150, 23);

        btnBack1.setText("<< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1);
        btnBack1.setBounds(30, 400, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateProfile;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsename;
    // End of variables declaration//GEN-END:variables

}
