/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.Profile;
import Business.Profiles.StudentProfile;
import Business.Profiles.FacultyProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class AdministerPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Person person;
    Profile createdProfile;
    Business business;
    ManagePersonsJPanel parent;

    public AdministerPersonJPanel(Business bz, Person p, ManagePersonsJPanel parent, JPanel jp) {
        CardSequencePanel = jp;
        this.business = bz;
        this.person = p;
        this.parent = parent;
        initComponents();

        populate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtFullName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        txtUsename = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnCreateProfile = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        lblUserName1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Manage Person Profile");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        btnSave.setText("Save Details");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(150, 200, 120, 23);
        add(txtFullName);
        txtFullName.setBounds(150, 80, 260, 23);
        add(txtEmail);
        txtEmail.setBounds(150, 120, 260, 30);
        add(txtPhone);
        txtPhone.setBounds(150, 160, 260, 23);

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblEmail.setText("Email");
        add(lblEmail);
        lblEmail.setBounds(30, 120, 80, 19);

        lblPhone.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblPhone.setText("Phone");
        add(lblPhone);
        lblPhone.setBounds(30, 160, 80, 19);

        lblFullName.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblFullName.setText("Full Name");
        add(lblFullName);
        lblFullName.setBounds(30, 80, 80, 19);

        lblUserName.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblUserName.setText("Username");
        add(lblUserName);
        lblUserName.setBounds(310, 280, 80, 19);

        lblRole.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblRole.setText("Role ");
        add(lblRole);
        lblRole.setBounds(30, 280, 60, 19);
        add(txtUsename);
        txtUsename.setBounds(400, 280, 160, 23);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee/Admin", "Faculty", "Student" }));
        add(cmbRole);
        cmbRole.setBounds(100, 280, 150, 23);

        btnCreate.setText("Create User Account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(400, 350, 160, 23);

        btnCreateProfile.setText("Create Profile");
        btnCreateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProfileActionPerformed(evt);
            }
        });
        add(btnCreateProfile);
        btnCreateProfile.setBounds(100, 350, 160, 23);

        btnBack1.setText("<< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1);
        btnBack1.setBounds(30, 420, 80, 23);

        lblUserName1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblUserName1.setText("Password");
        add(lblUserName1);
        lblUserName1.setBounds(310, 310, 80, 19);
        add(txtPassword);
        txtPassword.setBounds(400, 310, 160, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = txtFullName.getText();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Full name cannot be empty.",
                    "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        person.setName(name);
        person.setEmail(txtEmail.getText());
        person.setPhoneNumber(txtPhone.getText());
        parent.refreshTable();
        JOptionPane.showMessageDialog(this, "Person details saved.");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnCreateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProfileActionPerformed
        // TODO add your handling code here:

        if (createdProfile != null) {
            JOptionPane.showMessageDialog(this, "A profile already exists for this person.");
            return;
        }

        String role = (String) cmbRole.getSelectedItem();

        if (role.equals("Employee/Admin")) {
            createdProfile = business.getEmployeeDirectory().newEmployeeProfile(person);
        } else if (role.equals("Student")) {
            createdProfile = business.getStudentDirectory().newStudentProfile(person);
        } else if (role.equals("Faculty")) {
            createdProfile = business.getFacultydirectory().newFacultyProfile(person);
        } else {
            JOptionPane.showMessageDialog(this, "Please choose a valid role.");
            return;
        }

        JOptionPane.showMessageDialog(this, role + " profile created. Now create a user account.");

    }//GEN-LAST:event_btnCreateProfileActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        // Validation: profile must exist first
        if (createdProfile == null) {
            JOptionPane.showMessageDialog(this, "Create a profile (role) first.");
            return;
        }

        String un = txtUsename.getText();
        String pw = txtPassword.getText();

        if (un.isEmpty() || pw.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username and password are required.");
            return;
        }

        UserAccountDirectory uad = business.getUserAccountDirectory();
        if (uad.findByUsername(un) != null) {
            JOptionPane.showMessageDialog(this, "That username is already taken.");
            return;
        }

        UserAccount ua = uad.newUserAccount(createdProfile, un, pw);
        ua.setStatus("Active");

        if (createdProfile instanceof StudentProfile) {
            ((StudentProfile) createdProfile).setUserAccount(ua);
        } else if (createdProfile instanceof FacultyProfile) {
            ((FacultyProfile) createdProfile).setUserAccount(ua);
        }

        JOptionPane.showMessageDialog(this, "User account created.");

        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateProfile;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsename;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        txtFullName.setText(person.getName());
        txtEmail.setText(person.getEmail());
        txtPhone.setText(person.getPhoneNumber());
    }

}
